// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3b7pq8PWdp_mRL5unNqMXJhBtvIn8MaQ',
    appId: '1:1042321001518:web:e9f21bc7c3d2cec78963bf',
    messagingSenderId: '1042321001518',
    projectId: 'roadmap-1400d',
    authDomain: 'roadmap-1400d.firebaseapp.com',
    databaseURL: 'https://roadmap-1400d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roadmap-1400d.firebasestorage.app',
    measurementId: 'G-RCXFD94C68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfJ4HOA-1ypJkpyiCJF4mzNyM2Kne5-0w',
    appId: '1:1042321001518:android:a4d98b3015db6bc68963bf',
    messagingSenderId: '1042321001518',
    projectId: 'roadmap-1400d',
    databaseURL: 'https://roadmap-1400d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roadmap-1400d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiJXZCZ2i388SLmRtamUnAdYsBFzxX1cg',
    appId: '1:1042321001518:ios:286adebe28f252e38963bf',
    messagingSenderId: '1042321001518',
    projectId: 'roadmap-1400d',
    databaseURL: 'https://roadmap-1400d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roadmap-1400d.firebasestorage.app',
    iosBundleId: 'com.example.map',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiJXZCZ2i388SLmRtamUnAdYsBFzxX1cg',
    appId: '1:1042321001518:ios:286adebe28f252e38963bf',
    messagingSenderId: '1042321001518',
    projectId: 'roadmap-1400d',
    databaseURL: 'https://roadmap-1400d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roadmap-1400d.firebasestorage.app',
    iosBundleId: 'com.example.map',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3b7pq8PWdp_mRL5unNqMXJhBtvIn8MaQ',
    appId: '1:1042321001518:web:32ee6dbb1eca78918963bf',
    messagingSenderId: '1042321001518',
    projectId: 'roadmap-1400d',
    authDomain: 'roadmap-1400d.firebaseapp.com',
    databaseURL: 'https://roadmap-1400d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roadmap-1400d.firebasestorage.app',
    measurementId: 'G-Q06E5PDNRT',
  );
}
